global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: dip_backend
    static_configs:
      - targets: ["backend:9090"]

  - job_name: redis
    static_configs:
      - targets: ["redis:6379"]
